language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

before_script:
 # - npm install -g gulp


script:
  - hexo clean && hexo g


after_script:
  - cd ./public
  - git init
  - git config user.name "adoredee"
  - git config user.email "adoredeek@gmail.com"
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/adoredee/adoredee.github.io.git
             
